import { brandIconCollection } from "@/assets/icons/brand"

// Generated from https://github.com/iconify/icon-sets/tree/f452e4e0eb684bc42ece9daacb5b61800b8d9aa1/json
export type IconName =
  | `academicons:${string}`
  | `akar-icons:${string}`
  | `ant-design:${string}`
  | `arcticons:${string}`
  | `basil:${string}`
  | `bi:${string}`
  | `bpmn:${string}`
  | `brandico:${string}`
  | `bx:${string}`
  | `bxl:${string}`
  | `bxs:${string}`
  | `bytesize:${string}`
  | `carbon:${string}`
  | `charm:${string}`
  | `ci:${string}`
  | `cib:${string}`
  | `cif:${string}`
  | `cil:${string}`
  | `circle-flags:${string}`
  | `circum:${string}`
  | `clarity:${string}`
  | `codicon:${string}`
  | `covid:${string}`
  | `cryptocurrency-color:${string}`
  | `cryptocurrency:${string}`
  | `dashicons:${string}`
  | `devicon-line:${string}`
  | `devicon-original:${string}`
  | `devicon-plain:${string}`
  | `devicon:${string}`
  | `ei:${string}`
  | `el:${string}`
  | `emblemicons:${string}`
  | `emojione-monotone:${string}`
  | `emojione-v1:${string}`
  | `emojione:${string}`
  | `entypo-social:${string}`
  | `entypo:${string}`
  | `eos-icons:${string}`
  | `ep:${string}`
  | `et:${string}`
  | `eva:${string}`
  | `fa-brands:${string}`
  | `fa-regular:${string}`
  | `fa-solid:${string}`
  | `fa:${string}`
  | `fa6-brands:${string}`
  | `fa6-regular:${string}`
  | `fa6-solid:${string}`
  | `fad:${string}`
  | `fe:${string}`
  | `feather:${string}`
  | `file-icons:${string}`
  | `flag:${string}`
  | `flagpack:${string}`
  | `flat-color-icons:${string}`
  | `flat-ui:${string}`
  | `fluent-emoji-flat:${string}`
  | `fluent-emoji-high-contrast:${string}`
  | `fluent-emoji:${string}`
  | `fluent-mdl2:${string}`
  | `fluent:${string}`
  | `fontelico:${string}`
  | `fontisto:${string}`
  | `formkit:${string}`
  | `foundation:${string}`
  | `fxemoji:${string}`
  | `gala:${string}`
  | `game-icons:${string}`
  | `geo:${string}`
  | `gg:${string}`
  | `gis:${string}`
  | `gravity-ui:${string}`
  | `gridicons:${string}`
  | `grommet-icons:${string}`
  | `guidance:${string}`
  | `healthicons:${string}`
  | `heroicons-outline:${string}`
  | `heroicons-solid:${string}`
  | `heroicons:${string}`
  | `humbleicons:${string}`
  | `ic:${string}`
  | `icomoon-free:${string}`
  | `icon-park-outline:${string}`
  | `icon-park-solid:${string}`
  | `icon-park-twotone:${string}`
  | `icon-park:${string}`
  | `iconamoon:${string}`
  | `iconoir:${string}`
  | `icons8:${string}`
  | `il:${string}`
  | `ion:${string}`
  | `iwwa:${string}`
  | `jam:${string}`
  | `la:${string}`
  | `lets-icons:${string}`
  | `line-md:${string}`
  | `logos:${string}`
  | `ls:${string}`
  | `lucide:${string}`
  | `majesticons:${string}`
  | `maki:${string}`
  | `map:${string}`
  | `material-symbols-light:${string}`
  | `material-symbols:${string}`
  | `mdi-light:${string}`
  | `mdi:${string}`
  | `medical-icon:${string}`
  | `memory:${string}`
  | `meteocons:${string}`
  | `mi:${string}`
  | `mingcute:${string}`
  | `mono-icons:${string}`
  | `mynaui:${string}`
  | `nimbus:${string}`
  | `nonicons:${string}`
  | `noto-v1:${string}`
  | `noto:${string}`
  | `octicon:${string}`
  | `oi:${string}`
  | `ooui:${string}`
  | `openmoji:${string}`
  | `pajamas:${string}`
  | `pepicons-pencil:${string}`
  | `pepicons-pop:${string}`
  | `pepicons-print:${string}`
  | `pepicons:${string}`
  | `ph:${string}`
  | `pixelarticons:${string}`
  | `prime:${string}`
  | `ps:${string}`
  | `quill:${string}`
  | `radix-icons:${string}`
  | `raphael:${string}`
  | `ri:${string}`
  | `si-glyph:${string}`
  | `simple-icons:${string}`
  | `simple-line-icons:${string}`
  | `skill-icons:${string}`
  | `solar:${string}`
  | `streamline-emojis:${string}`
  | `streamline:${string}`
  | `subway:${string}`
  | `svg-spinners:${string}`
  | `system-uicons:${string}`
  | `tabler:${string}`
  | `tdesign:${string}`
  | `teenyicons:${string}`
  | `topcoat:${string}`
  | `twemoji:${string}`
  | `typcn:${string}`
  | `uil:${string}`
  | `uim:${string}`
  | `uis:${string}`
  | `uit:${string}`
  | `uiw:${string}`
  | `vaadin:${string}`
  | `vs:${string}`
  | `vscode-icons:${string}`
  | `websymbol:${string}`
  | `whh:${string}`
  | `wi:${string}`
  | `wpf:${string}`
  | `zmdi:${string}`
  | `zondicons:${string}`
  | `brand:${keyof (typeof brandIconCollection)["icons"]}`

export type IconData = {
  left: number
  top: number
  width: number
  height: number
  body: string
}
